export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  FACILITY_NOT_FOUND: "FACILITY_NOT_FOUND",
  FACILITY_ALREADY_DISABLED: "FACILITY_ALREADY_DISABLED",
  IMPACT_NOTE_REQUIRED: "IMPACT_NOTE_REQUIRED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
