export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  IMPACT_NOTE_REQUIRED: "IMPACT_NOTE_REQUIRED",
  FACILITY_NOT_FOUND: "FACILITY_NOT_FOUND",
  ALREADY_DEACTIVATED: "ALREADY_DEACTIVATED"
} as const;
